config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  root 'articles#index'
  get 'search' => 'articles#search'
  get 'inquiry' => 'inquiry#index'              # 入力画面
  post 'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post 'inquiry/thanks' => 'inquiry#thanks'     # 送信完了画面
  resources :articles, only:[:index, :show, :new, :create]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin_flg?
      can :access, :rails_admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  # usersテーブルとのアソシエーションです
  belongs_to :user

  # thumbnail登録時の設定です
  mount_uploader :thumbnail, ThumbnailUploader
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model #ここでActiveModelを読み込んで、DBと繋がらないモデルとしている

  attr_accessor :name, :email, :message #これ大事

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
  validates :message, :presence => {:message => 'お問い合わせ内容を記載して下さい'}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # articlesテーブルとのアソシエーションです
  has_many :articles, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all.order("created_at DESC").page(params[:page]).per(10)
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    article = Article.new(create_params)
    if article.save
      redirect_to articles_path
    else
      redirect_to new_article_path
    end
  end

  def search
    @articles = Article.where('title LIKE(?)',"%#{params[:title]}%").order("created_at DESC")
    respond_to do |format|
      format.html
      format.json
    end
  end

  private
  def create_params
    params.require(:article).permit(:title, :text, :thumbnail).merge(user_id: current_user.id)
  end
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def index
    # binding.pry
    # 入力画面を表示
    @inquiry = Inquiry.new
    render :action => 'index'
  end

  def confirm
    # 入力値のチェック
    # binding.pry
    @inquiry = Inquiry.new(params[:inquiry_params])
    # binding.pry
    if @inquiry.valid?
      # OK。確認画面を表示
      render :action => 'confirm'
    else
      # NG。入力画面を再表示
      render :action => 'index'
    end
  end

  def thanks
    # メール送信
    @inquiry = Inquiry.new(params[:inquiry])
    InquiryMailer.received_email(@inquiry).deliver
    # 完了画面を表示
    render :action => 'thanks'
  end

  private
  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_article.html.haml
%div.article
  %img.article__image{src: article.thumbnail }
  %div.article__texts
    %div.article__texts__title-box
      = link_to article_path(article.id), class: 'article__texts__title-box__title-link' do
        %p.article__texts__title-box__title= article.title
    %div.article__texts__text-box
      %p.article__texts__text-box__text
        =strip_tags(article.text).gsub(/(\r\n|\r|\n)/, '').gsub(/(\xc2\xa0|\s)+/, '')
    %p.article__texts__date= article.created_at.strftime('%Y.%m.%d')

app/views/articles/index.html.haml
%div.body
  %div.body__left
    = render partial: "article", collection: @articles
    = paginate(@articles)

  %div.body__right
    %img.ad{src: "https://lmcom.jp/wp/wp-content/uploads/2017/02/web-study-meeting6.jpg" }
    %div.popular-articles
      %p.popular-articles__title 人気記事ランキング
      %div.popular-articles__article
        %i.fa.fa-star-o.popular-articles__article__icon
        %p.popular-articles__article__ranking 1位
        %img.popular-articles__article__image{src: "http://tk.ismcdn.jp/mwimgs/c/e/570/img_ce9e9197e8c71adb4da2bf07a589c2ae192733.jpg" }
        %p.popular-articles__article__text 日本の大学を中退し、単身タイのタマサート大学へ !! 東南アジアに恋した大学生のリアル

      %div.popular-articles__article
        %i.fa.fa-star-o.popular-articles__article__icon
        %p.popular-articles__article__ranking 2位
        %img.popular-articles__article__image{src: "http://tk.ismcdn.jp/mwimgs/c/e/570/img_ce9e9197e8c71adb4da2bf07a589c2ae192733.jpg" }
        %p.popular-articles__article__text 日本の大学を中退し、単身タイのタマサート大学へ !! 東南アジアに恋した大学生のリアル

      %div.popular-articles__article
        %i.fa.fa-star-o.popular-articles__article__icon
        %p.popular-articles__article__ranking 3位
        %img.popular-articles__article__image{src: "http://tk.ismcdn.jp/mwimgs/c/e/570/img_ce9e9197e8c71adb4da2bf07a589c2ae192733.jpg" }
        %p.popular-articles__article__text 日本の大学を中退し、単身タイのタマサート大学へ !! 東南アジアに恋した大学生のリアル

      %div.popular-articles__article
        %i.fa.fa-star-o.popular-articles__article__icon
        %p.popular-articles__article__ranking 4位
        %img.popular-articles__article__image{src: "http://tk.ismcdn.jp/mwimgs/c/e/570/img_ce9e9197e8c71adb4da2bf07a589c2ae192733.jpg" }
        %p.popular-articles__article__text 日本の大学を中退し、単身タイのタマサート大学へ !! 東南アジアに恋した大学生のリアル

      %div.popular-articles__article
        %i.fa.fa-star-o.popular-articles__article__icon
        %p.popular-articles__article__ranking 5位
        %img.popular-articles__article__image{src: "http://tk.ismcdn.jp/mwimgs/c/e/570/img_ce9e9197e8c71adb4da2bf07a589c2ae192733.jpg" }
        %p.popular-articles__article__text 日本の大学を中退し、単身タイのタマサート大学へ !! 東南アジアに恋した大学生のリアル

app/views/articles/new.html.haml
%div.body-new
  = form_for @article, html:{class: 'body-new__form', :multipart => true } do |f|
    = f.text_field :title, class: 'body-new__form__title', placeholder: '記事タイトル（４８字以内）', maxlength: 48
    = f.cktext_area :text, class: 'body-new__form__text'

    %div.body-new__form__thumbnail
      %p.body-new__form__thumbnail__title サムネイル画像
      %div.body-new__form__thumbnail__icon-box
        %div.body-new__form__thumbnail__icon-box__select
          %label{for: "thumbnail", class: "fa fa-picture-o fa-5x comment-form__icon" }
            = f.file_field :thumbnail, id: 'thumbnail', style: 'display: none;', class: "file"
          %p.body-new__form__thumbnail__icon-box__select__notice +画像を選択

    %input.body-new__form__button{type: "submit", value: "Sent"}/

app/views/articles/show.html.haml
%div.body-show
  %div.body-show__left
    %p.body-show__left__title= @article.title
    %img.body-show__left__img{src: @article.thumbnail}
    %div.body-show__left__text
      != @article.text
    %img.ad-left{src: "https://lmcom.jp/wp/wp-content/uploads/2017/02/web-study-meeting6.jpg" }
    %img.ad-right{src: "https://lmcom.jp/wp/wp-content/uploads/2017/02/web-study-meeting6.jpg" }
    / %p.body-show__left__same-categories 同じカテゴリーの人気記事


  %div.body-show__right
    %img.ad{src: "https://lmcom.jp/wp/wp-content/uploads/2017/02/web-study-meeting6.jpg" }
    %div.popular-articles
      %p.popular-articles__title 人気記事ランキング
      %div.popular-articles__article
        %i.fa.fa-star-o.popular-articles__article__icon
        %p.popular-articles__article__ranking 1位
        %img.popular-articles__article__image{src: "http://tk.ismcdn.jp/mwimgs/c/e/570/img_ce9e9197e8c71adb4da2bf07a589c2ae192733.jpg" }
        %p.popular-articles__article__text 日本の大学を中退し、単身タイのタマサート大学へ !! 東南アジアに恋した大学生のリアル

      %div.popular-articles__article
        %i.fa.fa-star-o.popular-articles__article__icon
        %p.popular-articles__article__ranking 2位
        %img.popular-articles__article__image{src: "http://tk.ismcdn.jp/mwimgs/c/e/570/img_ce9e9197e8c71adb4da2bf07a589c2ae192733.jpg" }
        %p.popular-articles__article__text 日本の大学を中退し、単身タイのタマサート大学へ !! 東南アジアに恋した大学生のリアル

      %div.popular-articles__article
        %i.fa.fa-star-o.popular-articles__article__icon
        %p.popular-articles__article__ranking 3位
        %img.popular-articles__article__image{src: "http://tk.ismcdn.jp/mwimgs/c/e/570/img_ce9e9197e8c71adb4da2bf07a589c2ae192733.jpg" }
        %p.popular-articles__article__text 日本の大学を中退し、単身タイのタマサート大学へ !! 東南アジアに恋した大学生のリアル

      %div.popular-articles__article
        %i.fa.fa-star-o.popular-articles__article__icon
        %p.popular-articles__article__ranking 4位
        %img.popular-articles__article__image{src: "http://tk.ismcdn.jp/mwimgs/c/e/570/img_ce9e9197e8c71adb4da2bf07a589c2ae192733.jpg" }
        %p.popular-articles__article__text 日本の大学を中退し、単身タイのタマサート大学へ !! 東南アジアに恋した大学生のリアル

      %div.popular-articles__article
        %i.fa.fa-star-o.popular-articles__article__icon
        %p.popular-articles__article__ranking 5位
        %img.popular-articles__article__image{src: "http://tk.ismcdn.jp/mwimgs/c/e/570/img_ce9e9197e8c71adb4da2bf07a589c2ae192733.jpg" }
        %p.popular-articles__article__text 日本の大学を中退し、単身タイのタマサート大学へ !! 東南アジアに恋した大学生のリアル

app/views/inquiry/confirm.html.haml
.page-header
  %h1 お問い合わせ
= form_for @inquiry, :url => inquiry_thanks_path do |f|
  %table.table
    %tr
      %th 名前
      %td
        = f.hidden_field :name
        = @inquiry.name
    %tr
      %th メールアドレス
      %td
        = f.hidden_field :email
        = @inquiry.email
    %tr
      %th お問い合わせ内容
      %td
        = f.hidden_field :message
        = simple_format(@inquiry.message)
  = f.submit '送信', :class => 'btn btn-primary'

app/views/inquiry/index.html.haml
%div.inquiry
  = form_for @inquiry, :url => inquiry_confirm_path do |f|
    .page-header
      %h1 お問い合わせ
    - if @inquiry.errors.any?
      .alert.alert-danger{:role => "alert"}
        %strong 入力内容にエラーがあります
        %ul
          - @inquiry.errors.each do |attr, msg|
            %li= msg

    %div.table
      %div.box
        %p.title
          名前
          %span.text-danger （必須）
        = f.text_field :name, class: "field"

      %div.box
        %p.title
          メールアドレス
          %span.text-danger （必須）
        = f.text_field :email, class: "field"

      %div.box
        %p.title お問い合わせ内容
        = f.text_area :message, class: "field-text"
    = f.submit '送信', class: 'btn btn-primary'

app/views/inquiry/thanks.html.haml
.page-header
  %h1 お問い合わせ
%p
  お問い合わせいただきありがとうございました。

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %title Diver
    = csrf_meta_tags
    = stylesheet_link_tag    'application'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header
      %div.header-top
        %i.fa.fa-tags
        = link_to root_path do
          %p.header-top__service-name Diver
        %div.header-top__sns-for-smartphone
          %i.fa.fa-twitter-square
          %i.fa.fa-facebook-square
        %div.header-top__inputs
          %input{type: 'text', placeholder: '記事を検索する', class: 'search' }
        - if user_signed_in? && current_user.id === 1
          %div.header-top__sns
            = link_to rails_admin.dashboard_path do
              %i.fa.fa-address-card
            = link_to new_article_path do
              %i.fa.fa-pencil-square
            = link_to destroy_user_session_path, method: :delete do
              %i.fa.fa-window-close
            %i.fa.fa-twitter-square
            = link_to user_session_path do
              %i.fa.fa-facebook-square
        - else
          %div.header-top__sns
            %i.fa.fa-twitter-square
            = link_to user_session_path do
              %i.fa.fa-facebook-square
      %div.toggle
        %i.fa.fa-bars.menu-bar
      %ul.header-bottom
        = link_to root_path, class: 'header-bottom__links-link' do
          %li.header-bottom__links トップ
        %li.header-bottom__links ビジネス
        %li.header-bottom__links ファッション
        %li.header-bottom__links スポーツ
        = link_to inquiry_path do
          %li.header-bottom__links.contact お問い合わせ


    = yield